### ISSUE TITLE
Radio - fix misalignments/errors

### ISSUE THREAD

**Issue by thrbnhrtmnn** [deven-org/B01LER-Kitchen#586]
#### Description / User Story

----
#### Acceptance Criteria
- [x] ~Implement different sizing tokens (MD & LG) for .input-control and the icon (:before)~ > split to #764
- [x] ~Prevent click in readOnly and also prevent a selection via focusing a control, but focusing still is possible in readonly state~ > split to #765
- [x] ~Would be nice to have an *optional* max-width for .blr-radio~ > split to #764
- [x] ~Allow active option in error state~ > split to #765
- [x] ~It should be possible to predefine a selected option - setting to disabled or readonly always resets~ can be done when checked prop functions (part of #765)
- [x] ~Separate radio css and move them to their component folders~ > split to #766
- [x] ~Fix color of focus ring in light and dark mode (it is blue but should be black in light and white in dark mode)~ > split to #766

----
#### Background information
- 
- ...

**Comment by thrbnhrtmnn** [comment]
Open topics were split into multiple tickets
