### ISSUE TITLE
Checkbox - fix misalignments/errors

### ISSUE THREAD

**Issue by thrbnhrtmnn** [deven-org/B01LER-Kitchen#599]
#### Description / User Story

The following differences were found when comparing the Checkbox in Storybook with the Checkbox in Design:

Label:
- [x] Font Color for default and readonly state in light mode is wrong, currently it is hsl220 instead of hsl216 like in design >  it is now always #17191c
- [x] Font Color for disabled state is wrong in light and dark mode, currently it is hsl220 instead of hsl212 like in design for light mode and hsl220 instead of hsl219 like in design for dark mode > it is now c7cad1 in light and #5c6370 in dark mode
- [x] Font Color for error state is wrong in light and dark mode, currently it is black (hsl220) instead of red (hsl350) like in design

Control:
- [x] The border of the control is applied outside of the control element in code, but inside the control element in design, making the control bigger in code than in design, and also slightly misaligned with the label
- [x] Hover state for unchecked control is missing in light and dark mode
- [x] Control color is wrong when focusing the control while in the readonly state
- [x] ~There is no focus ring when focusing the control while in the readonly state~ > part of #752 
- [x] ~Focus ring already gets applied when pressing, but in design it is not there in pressed state~ > part of #751 and follow up tasks
- [x] ~Focus ring is much rounder than in design, especially on the inside (2px in design and 4px in code?)~ > part of #752 
- [x] In dark mode rest state a border is displayed in code that is not there in design, the border is not there in other states (hover, pressed, focus state, readonly, disabled, error)
- [x] In dark mode the focus ring is black and not white like in design (probably part of #330 ?)
- [x] The color of the checkmark is wrong in dark mode readonly and disabled state, in design it is black
- [x] The control is not square anymore, when the label gets so long that it needs to break into another line > part of #754

Behaviour:
- [x] Readonly state is not working, input is still possible

----
#### Acceptance Criteria
- [ ] _Acceptance criteria 1_
- [ ] [Props Excel](https://ts.accenture.com/:x:/r/sites/b01ler-core/Shared%20Documents/Documentation_Props.xlsx?d=wb2cc9fb85c3940499652a4e6bbe09ef1&csf=1&web=1&e=bhRYao) has been updated / comments have been resolved and props changed from red to black font color > @thrbnhrtmnn or @angelicahoyss can support here

----
#### Background information

- Other things found in the checkbox:
   - ~There is an area between the control and the label where neither the hover nor pressed state get applied and it is not possible to check/uncheck the component. Is this intended by design?~ > fixed
   - ~The focus state initially only has a 1px border, which gets corrected to 2px after a short delay, also I assume the color in dark mode will be fixed with https://github.com/deven-org/B01LER-Kitchen/issues/330~ > fixed
   - ~Should the component not be clickable anymore, when it has an error state?~ > fixed

**Comment by thrbnhrtmnn** [comment]
All ACs are already fixed or are part of other tasks
